---
- name: Install required packages
  ansible.builtin.package:
    name:
      - sudo
      - php
      - apache2
      - git
      - qemu-guest-agent
      - vim
      - curl
      - net-tools
      - figlet
      - dnsutils
      - python3-apt
      - nfs-common
      - man
      - w3m
    state: present
    update_cache: true

- name: Enable the Apache2 module rewrite
  community.general.apache2_module:
    state: present
    name: rewrite

- name: Write the apache config file
  ansible.builtin.copy:
    src: 000-default.conf
    dest: /etc/apache2/sites-available
  notify:
  - Restart apache

- name: Enable Apache conf
  ansible.builtin.command: a2ensite 000-default
  failed_when: false
  changed_when: false
  notify:
  - Restart apache

#  failed_when: false
#  changed_when: false
#  notify:
#  - Restart apache

#- name: Ensure apache is running
#  ansible.builtin.service:
#    name: httpd
#    state: started

###
# cp -f /root/000-default.conf /etc/apache2/sites-available/
# cd /etc/apache2/sites-enabled
# rm -f 000-default.conf
# ln -s ../sites-available/000-default.conf .

### enable re-write engine module
# a2enmod rewrite
#
