---
#
# ansible-playbook -i docker0,docker1 install_docker.ym
#
- name: Install docker on debian
  hosts: all
  remote_user: judge
  become: true

  tasks:
  - name: Install dependencies
    ansible.builtin.apt:
      name:
        - apt-transport-https,
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
        - python3-pip
      state: present
      update_cache: true

  # Install (docker-compose) for Python 3
  - name: Install docker-compose
    ansible.builtin.pip:
      name: docker-compose
      executable: pip3

  - name: Add Docker GPG apt Key
    ansible.builtin.apt_key:
      url: https://download.docker.com/linux/debian/gpg
      state: present

  - name: LSB release value
    ansible.builtin.command: lsb_release -cs
    register: debian_name
    changed_when: debian_name.rc == 0
    failed_when: debian_name.rc != 0

  - name: Add Docker Repository
    ansible.builtin.apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/debian {{ debian_name.stdout }} stable
      state: present
    register: apt_repository_output

  - name: Update apt cache
    ansible.builtin.apt:
      update_cache: true
      state: present

  - name: Install docker-ce docker-ce-cli containerd.io
    ansible.builtin.apt:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
      state: present


# from https://docs.docker.com/engine/install/debian/
#
# sudo apt install apt-transport-https  ca-certificates  curl  gnupg-agent  software-properties-common
# curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -
# sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
# sudo apt-get update
# sudo apt-get install docker-ce docker-ce-cli containerd.io
#
