---
#
# install my own motd
# ansible-playbook playbook/install_motd.yml
#
- name: Install motd
  hosts: production
  remote_user: judge
  become: true

  tasks:
  - name: Install dependencies
    ansible.builtin.apt:
      name: figlet
      state: present
      update_cache: true

  - name: Copy roman.flf
    ansible.builtin.copy:
      src: files/roman.flf
      dest: /usr/share/figlet/roman.flf
      owner: root
      group: root
      mode: '0644'

  - name: Copy 05-banner
    ansible.builtin.copy:
      src: files/05-banner
      dest: /etc/update-motd.d/05-banner
      owner: root
      group: root
      mode: 0755

  - name: Copy 06-os-release
    ansible.builtin.copy:
      src: files/06-os-release
      dest: /etc/update-motd.d/06-os-release
      owner: root
      group: root
      mode: 0755

  - name: Copy empty motd file
    ansible.builtin.copy:
      src: files/motd
      dest: /etc/motd
      owner: root
      group: root
      mode: '0644'

  - name: Disable PrintLastLog in sshd_config
    ansible.builtin.replace:
      path: /etc/ssh/sshd_config
      regexp: '^#PrintLastLog yes$'
      replace: 'PrintLastLog no'

  # should really be using a _handler_ for this one
  - name: Restart service sshd, in all cases
    ansible.builtin.service:
      name: sshd
      state: restarted
