---
#
# ansible-playbook  -i vmdocker,vmsmb,firefox,debianjet,gallery,torrent  min_setup.yml
#
- name: Copy .vimrc .bash_aliases an install minimum packages
  hosts: production
  remote_user: judge
  become: true

  tasks:
  - name: Copy stuff to /home/judge
    ansible.builtin.copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      mode: '0644'
    with_list:
      - src: ../files/my.vimrc
        dest: ~/.vimrc
      - src: ../files/my.bash_aliases
        dest: ~/.bash_aliases
    become: false

  - name: Copy stuff to /root/
    ansible.builtin.copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      mode: '0644'
    with_list:
      - src: ../files/my.vimrc
        dest: ~/.vimrc
      - src: ../files/my.bash_aliases
        dest: ~/.bash_aliases

  - name: Install default packages (vim, git, man, curl, qemu-guest-agent)
    ansible.builtin.apt:
      name:
        - python3-apt
        - vim
        - git
        - man
        - curl
        - qemu-guest-agent
      state: present
      update_cache: true
#
