---
#
# ansible-playbook -i inventory/hosts ping.yml
# ansible-playbook ping.yml
#
- name: Ping test
  hosts: production,arch
  remote_user: judge

  tasks:
  - name: Ping test selected machines
    ansible.builtin.ping:
#
